name: Syntax Check

on:
  push:
    branches:
      - master

jobs:
  syntax_check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build with analyzers
      run: dotnet build --no-restore /p:RunAnalyzersDuringBuild=true /p:WarningLevel=0
