name: Syntax Check

on:
  push:
    branches:
      - master

jobs:
  syntax_check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Add StyleCop.Analyzers package
      run: dotnet add package StyleCop.Analyzers --version 1.1.118

    - name: Check code
      run: |
        dotnet build /p:StyleCopEnable=true
